// create-react-app/src/FeatureList.js
import { useGetFeatures } from "@usebool/sdk-react";
import { Badge } from './Badge';

const ItemDetails = ({ featureKey, value}) => {
    return (
        <>
            <dt>{featureKey}</dt>
            <dd>{value}</dd>
        </>
    );
}

const Item = ({ feature }) => {
    return (
        <li className="list-item">
            <strong>{feature.name}</strong>
            <span><Badge value={feature.value} /></span>
            <details>
            <summary>
                Details
            </summary>
            <dl>
                <ItemDetails featureKey="key" value={feature.key} />
                <ItemDetails featureKey="description" value={feature.description} />
                <ItemDetails featureKey="id" value={feature.id} />
                <ItemDetails featureKey="applicationId" value={feature.applicationId} />
            </dl>
            </details>
        </li>
    );
}

export const FeatureList = () => {
    const features = useGetFeatures();

    return (
        <ul id="list">
            {features.map((feature) => (<Item key={feature.key} feature={feature} />))}
        </ul>
    );
}

// vue/src/components/FeatureList.vue
<script setup lang="ts">
import type { FeatureFlag } from '../types';
import Badge from './Badge.vue';
import DetailsItem from './DetailsItem.vue';

type Props = {
  features: FeatureFlag[];
};

defineProps<Props>();
</script>

<template>
  <ul id="list">
    <li
      v-for="feature in features"
      class="list-item"
      :test-id="`list-item-${feature.key}`"
    >
      <strong test-id="list-item-name">{{ feature.name }}</strong>

      <span test-id="list-item-value">
        <Badge :value="feature.value" />
      </span>

      <details>
        <summary>Details</summary>

        <dl>
          <DetailsItem keyName="key" :value="feature.key" />
          <DetailsItem keyName="description" :value="feature.description" />
          <DetailsItem keyName="id" :value="feature.id" />
          <DetailsItem keyName="applicationId" :value="feature.applicationId" />
        </dl>
      </details>
    </li>
  </ul>
</template>
